name: rtb
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - anyio=4.11.0
  - aom=3.6.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - autobahn=24.4.2
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - blas=1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli-python=1.0.9
  - bullet=3.25
  - bullet-cpp=3.25
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.3
  - comm=0.2.3
  - contourpy=1.3.1
  - cryptography=46.0.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - daqp=0.7.1
  - dav1d=1.2.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - distlib=0.4.0
  - eigen=3.4.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - ffmpeg=4.4.0
  - filelock=3.19.1
  - fontconfig=2.15.0
  - fonttools=4.59.2
  - fqdn=1.5.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozenlist=1.7.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.13
  - graphite2=1.3.14
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=10.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - hyperlink=21.0.0
  - icu=73.1
  - identify=2.6.14
  - idna=3.10
  - imageio=2.37.0
  - imageio-ffmpeg=0.6.0
  - importlib-metadata=8.7.0
  - intel-openmp=2023.0.0
  - ipykernel=6.30.1
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9f
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter=1.1.1
  - jupyter-lsp=2.3.0
  - jupyter-server-proxy=4.4.0
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.9
  - jupyterlab-vpython=3.1.8
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lame=3.100
  - lark=1.3.0
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libavif=1.1.1
  - libblas=3.9.0
  - libcups=2.4.2
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libiconv=1.16
  - libkrb5=1.21.3
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libopengl=1.7.0
  - libosqp=0.6.3
  - libpciaccess=0.18
  - libpng=1.6.39
  - libpq=17.4
  - libqdldl=0.1.7
  - libsodium=1.0.20
  - libstdcxx=15.1.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libvpx=1.11.0
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - markupsafe=3.0.3
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mesalib=25.1.5
  - mistune=3.1.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.6.3
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.6
  - nodeenv=1.9.1
  - notebook=7.4.7
  - notebook-shim=0.2.4
  - numpy=2.0.1
  - numpy-base=2.0.1
  - numpy-stl=3.2.0
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.10
  - openssl=3.5.3
  - osqp=0.6.7.post3
  - overrides=7.7.0
  - packaging=25.0
  - pandocfilters=1.5.0
  - parso=0.8.5
  - pcre2=10.42
  - pexpect=4.9.0
  - pgraph-python=0.6.3
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.4.0
  - pre-commit=4.3.0
  - pre_commit=4.3.0
  - progress=1.6.1
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - propcache=0.3.1
  - proxsuite=0.7.2
  - psutil=7.1.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybullet=3.25
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.0
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - pysocks=1.7.1
  - python=3.11.13
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python-utils=3.9.1
  - python_abi=3.11
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qdldl-python=0.1.7.post5
  - qpsolvers=4.8.1
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwayland=6.9.2
  - qtwebchannel=6.9.2
  - qtwebsockets=6.9.2
  - readline=8.3
  - referencing=0.36.2
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - roboticstoolbox-python=1.1.1
  - rpds-py=0.27.1
  - rtb-data=1.0.1
  - scipy=1.16.0
  - scs=3.2.7.post2
  - send2trash=1.8.3
  - setuptools=78.1.1
  - simde=0.8.2
  - simpervisor=1.0.0
  - sip=6.12.0
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.8
  - spatialgeometry=1.1.0
  - spatialmath-python=1.1.14
  - sphinxcontrib-jsmath=1.0.1
  - spirv-tools=2025.1
  - sqlite=3.50.2
  - stack_data=0.6.3
  - swift-sim=1.1.0
  - sympy=1.14.0
  - tbb=2021.8.0
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.15
  - tomli=2.2.1
  - tornado=6.5.1
  - traitlets=5.14.3
  - txaio=25.9.2
  - types-python-dateutil=2.9.0.20250822
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - ukkonen=1.0.1
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - virtualenv=20.34.0
  - vpython=7.6.5
  - wayland=1.24.0
  - wcwidth=0.2.14
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - x264=1!161.3030
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.20.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - ansitable==0.11.4
      - cfgv==3.4.0
      - colored==2.3.1
      - pandas==2.3.2
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.17
      - pyqt5-sip==12.17.1
      - pyqtwebengine==5.15.7
      - pyqtwebengine-qt5==5.15.17
      - pyserial==3.5
      - rtb==0.1.0
      - tqdm==4.67.1
      - tzdata==2025.2
      - websockets==10.4